name: Test Pipeline

on:
    push:
        branches:
        - master
    workflow_dispatch:
jobs:
    test: 
        runs-on: ubuntu-latest

        steps:
         - name: Checkout İslemi
           uses: actions/checkout@v4
         - name: Enviromentleri listele
           run: printenv
           #yeni komit isledi mi bak bakim
    
